(require 'package)
(package-initialize)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(coffee-tab-width 2)
 '(dabbrev-case-fold-search nil)
 '(enh-ruby-bounce-deep-indent nil)
 '(enh-ruby-deep-indent-paren-style nil)
 '(erc-autojoin-channels-alist (quote (("freenode.net" "#haskell-lens" "#purescript" "#emacs" "#haskell" "#nothaskell" "#atunit" "##guitar"))))
 '(erc-modules (quote (autojoin button completion fill irccontrols list match menu move-to-prompt netsplit networks noncommands readonly ring services stamp track)))
 '(erc-nick "NemesisD")
 '(erc-prompt-for-nickserv-password t)
 '(erc-server-auto-reconnect t)
 '(erc-server-reconnect-attempts 5)
 '(flycheck-disabled-checkers (quote (make emacs-lisp-checkdoc)))
 '(flycheck-display-errors-function (quote ignore))
 '(flycheck-global-modes (quote (not org-mode haskell-mode)))
 '(flycheck-haskell-runhaskell "runhaskell")
 '(flycheck-rubocop-lint-only t)
 '(haskell-align-imports-pad-after-name nil)
 '(haskell-interactive-mode-scroll-to-bottom t)
 '(haskell-mode-contextual-import-completion nil)
 '(haskell-process-auto-import-loaded-modules t)
 '(haskell-process-check-cabal-config-on-load t)
 '(haskell-process-log t)
 '(haskell-process-suggest-add-package nil)
 '(haskell-process-suggest-language-pragmas nil)
 '(haskell-process-suggest-overloaded-strings nil)
 '(haskell-process-suggest-remove-import-lines t)
 '(haskell-process-type (quote cabal-repl))
 '(haskell-stylish-on-save nil)
 '(haskell-tags-on-save t)
 '(ido-auto-merge-work-directories-length -1)
 '(indent-tabs-mode nil)
 '(inferior-haskell-wait-and-jump t)
 '(inhibit-startup-screen t)
 '(initial-buffer-choice t)
 '(js-indent-level 2)
 '(json-reformat:indent-width 2)
 '(magit-diff-use-overlays nil)
 '(magit-use-overlays nil)
 '(org-export-backends (quote (ascii html icalendar latex md)))
 '(org-mobile-directory "~/Dropbox/org/MobileOrg")
 '(org-src-fontify-natively t)
 '(package-archives (quote (("marmalade" . "http://marmalade-repo.org/packages/") ("gnu" . "http://elpa.gnu.org/packages/") ("melpa" . "http://melpa.milkbox.net/packages/"))))
 '(popwin:special-display-config (quote ((ag-mode :stick t) ("*All*" :height 15 :noselect t) ("*Flycheck error messages*" :regexp nil :height 15 :noselect t) ("*haskell-process-log*" :regexp nil :height 15 :noselect nil) ("*undo-tree*" :height 15 :noselect t) ("*Compile-Log*" :height 15 :noselect t) ("*Process List*" :height 15 :noselect t) ("*ag search" :height 15 :noselect t :stick t) ("*All*" :height 15 :noselect t) ("*undo-tree*" :height 15 :noselect t) ("*Compile-Log*" :height 15 :noselect t) ("*Backtrace*" :height 15 :noselect t) ("*Messages*" :height 15 :noselect t) ("*Process List*" :height 15 :noselect t :stick nil) ("*Warnings*" :height 15 :noselect nil :stick t) ("*Miniedit Help*" :noselect t) (help-mode :stick t) (completion-list-mode :noselect t) (compilation-mode :noselect t) (grep-mode :noselect t) (occur-mode :noselect t) ("*Pp Macroexpand Output*" :noselect t) ("*Shell Command Output*") ("*vc-diff*") ("*vc-change-log*") (" *undo-tree*" :width 60 :position right) ("^\\*anything.*\\*$" :regexp t) ("*slime-apropos*") ("*slime-macroexpansion*") ("*slime-description*") ("*slime-compilation*" :noselect t) ("*slime-xref*") (sldb-mode :stick t) (slime-repl-mode) (slime-connection-list-mode) ("*HS-Error*" :height 15 :noselect t))))
 '(projectile-switch-project-action (quote dired-cwd))
 '(restclient-log-request t)
 '(safe-local-variable-values (quote ((flycheck-disabled-checkers (quote haskell-ghc)) (require-final-newline))))
 '(show-trailing-whitespace t)
 '(sp-autoescape-string-quote nil)
 '(sp-ignore-modes-list (quote (minibuffer-inactive-mode erc-mode)))
 '(sql-product (quote postgres))
 '(sql-server "localhost")
 '(suggest-key-bindings t)
 '(tab-stop-list (quote (2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32)))
 '(tab-width 2)
 '(tags-case-fold-search nil)
 '(tags-revert-without-query t)
 '(typescript-indent-level 2)
 '(warning-minimum-level :warning)
 '(warning-minimum-log-level :debug)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-disable-auto-opening t)
 '(web-mode-disable-auto-pairing t)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-sql-indent-offset 2)
 '(yas-indent-line (quote fixed))
 '(yas-prompt-functions (quote (yas-ido-prompt yas-completing-prompt yas-x-prompt yas-dropdown-prompt yas-no-prompt))))

(load "~/.emacs.d/general_config.el")
(load "~/.emacs.d/blog_config.el")
(load "~/.emacs.d/haskell_config.el")
(load "~/.emacs.d/purescript_config.el")
(load "~/.emacs.d/ruby_config.el")
(load "~/.emacs.d/typescript_config.el")
(load "~/.emacs.d/web_config.el")
(load "~/.emacs.d/org_config.el")
(load "~/.emacs.d/terminal_config.el")

(provide 'emacs)
;;; .emacs ends here
(put 'narrow-to-region 'disabled nil)
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(put 'upcase-region 'disabled nil)
